### CREATE GOAL
POST http://192.168.1.68:3333/goals
Content-Type: application/json

{
  "title": "Tocar violao",
  "desiredWeeklyFrequency": 4
}

### CREATE GOAL COMPLETION
POST http://192.168.1.68:3333/completions
Content-Type: application/json

{
  "goalId": "qcnk2gflntk106pbi5l8odxb"
}

### GET PENDING GOALS
GET http://192.168.1.68:3333/pending-goals

### GET SUMMARY
GET http://192.168.1.68:3333/summary
